name: Build Rust EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # 允许手动点击按钮触发

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # --- 编译步骤 ---
    - name: Build Release
      run: cargo build --release --verbose

    # --- 上传结果 ---
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-app-exe
        # 这里的 rustby9527.exe 请确保和你的 Cargo.toml 里的名字一致
        path: target/release/rustby9527.exe
