        路径: target/release/rustby9527.exe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # --- 步骤 1：安装 vcpkg 和静态依赖 ---
    - name: Setup vcpkg Static Deps
      run: |
        # 1. 克隆 vcpkg
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        
        # 2. 配置清华镜像源 (防止下载超时)
        @"
        {
          "registries": [
            {
              "kind": "git",
              "repository": "https://mirrors.tuna.tsinghua.edu.cn/git/vcpkg/ports.git",
